/*
 *  author: Suhas Vittal
 *  date:   12 March 2026
 * */

#ifndef SIM_DRIVER_RDR_h
#define SIM_DRIVER_RDR_h

#include "instruction.h"
#include "sim/compute_subsystem.h"

#include <limits>
#include <queue>
#include <unordered_set>

namespace sim
{
namespace driver
{

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

class ROTATION_DIRECTED_RUNAHEAD
{
public:
    using inst_ptr = INSTRUCTION*;
    
    struct dag_data
    {
        DAG*   dag;
        size_t current_layer{0};

        /*
         * We want to track which rotation instructions a future rotation
         * is dependent on as we scan the DAG. This data structure stores
         * this information.
         * */
        std::vector<std::vector<qubit_type>> dependencies;

        /*
         * This data structure estimates the "time" before a rotation
         * for each qubit. Like `dependencies`, this is updated as we
         * scan the DAG
         * */
        std::vector<int> times;

        dag_data() =default;
        dag_data(const CLIENT*);

        std::vector<inst_ptr> do_initial_traversal();
        inst_ptr traverse_on_interrupt(inst_ptr);
        inst_ptr traverse_to_successor(inst_ptr);
    };

    struct request_type
    {
        inst_ptr inst;

        /*
         * This is the qubit assigned to preparing the rotation magic state
         * */
        QUBIT* pinned_qubit{nullptr};

        /*
         * `interrupted` indicates if `inst` is currently at the head of the DAG.
         * */
        bool interrupted{false};
    };

    /*
     * Statistics:
     * */

    uint64_t s_invalidated_in_queue{0};
    uint64_t s_requests{0};
    uint64_t s_requests_completed{0};
    uint64_t s_requests_invalidated{0};

    uint64_t s_completion_buffer_occupancy_sum{0};
    uint64_t s_completion_buffer_occupancy_ticks{0};
private:
    /*
     * Stores information about a client's dag in this data structure.
     * There is one entry per client.
     * */
    std::vector<dag_data> dag_info_;

    /*
     * Requests generated by reading the DAG are placed here.
     * */
    std::deque<request_type> request_queue_;

    /*
     * `free_qubits_` correspond to un-pinned qubits that can be assigned
     * to request in the `request_queue_`.
     *
     * `active_requests_` correspond to requests with pinned qubits.
     * */
    std::vector<QUBIT*> free_qubits_;
    std::vector<request_type> active_requests_;

    /*
     * `completion_buffer_` contains all completed requests.
     * */
    std::unordered_set<inst_ptr> completion_buffer_;

    COMPUTE_SUBSYSTEM* compute_subsystem_;
public:
    ROTATION_DIRECTED_RUNAHEAD(COMPUTE_SUBSYSTEM*, std::vector<CLIENT*>);

    long operate();
private:

};

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

} // namespace driver
} // namespace sim


#endif // SIM_DRIVER_RDR_h
