/*
 *  author: Suhas Vittal
 *  date:   12 March 2026
 * */

#ifndef SIM_DRIVER_RDR_h
#define SIM_DRIVER_RDR_h

#include "instruction.h"
#include "sim/client.h"
#include "sim/compute_subsystem.h"

#include <deque>
#include <unordered_set>
#include <vector>

namespace sim
{
namespace driver
{

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

class ROTATION_DIRECTED_RUNAHEAD
{
public:
    using inst_ptr = INSTRUCTION*;

    struct request_type
    {
        CLIENT* client;
        inst_ptr inst{nullptr};
        size_t dag_layer;

        /*
         * This is the qubit assigned to preparing the rotation magic state
         * */
        QUBIT* pinned_qubit{nullptr};

        bool interrupted{false};
        bool invalidated{false};
        bool done{false};

        cycle_type expected_start_cycle;

        cycle_type install_cycle;
        cycle_type rdr_start_cycle;
        cycle_type rdr_end_cycle;
        cycle_type cb_install_cycle;
    };

    /*
     * Metadata for completion buffer entries (i.e., for stats)
     * */
    using metadata_type = request_type;

    enum class APPLY_MAGIC_STATE_RESULT { GOOD, NEEDS_CORRECTION, ROUTING_CONTENTION };

    /*
     * Statistics:
     * */

    uint64_t s_requests_submitted{0};
    uint64_t s_requests_invalidated_before_issue{0};
    uint64_t s_requests_started{0};
    uint64_t s_requests_completed{0};
    uint64_t s_requests_interrupted{0};
    uint64_t s_requests_invalidated{0};
    uint64_t s_requests_used{0};

    uint64_t s_request_uop_sum{0};

    uint64_t s_request_completion_cycles_sum{0};
    uint64_t s_post_completion_idle_time_sum{0};

    uint64_t s_completion_buffer_occu_sum{0};
    uint64_t s_completion_buffer_occu_ticks{0};
private:
    /*
     * Requests generated by reading the DAG are placed here.
     * */
    std::deque<request_type> request_queue_;

    /*
     * `free_qubits_` correspond to un-pinned qubits that can be assigned
     * to request in the `request_queue_`.
     *
     * `active_requests_` correspond to requests with pinned qubits.
     * */
    std::vector<QUBIT*> free_qubits_;
    std::vector<request_type> active_requests_;

    /*
     * `completion_buffer_` contains all completed requests.
     * */
    std::unordered_map<inst_ptr, metadata_type> completion_buffer_;

    COMPUTE_SUBSYSTEM* compute_subsystem_;

    ssize_t lookahead_depth_;
public:
    ROTATION_DIRECTED_RUNAHEAD(COMPUTE_SUBSYSTEM*);

    long operate();

    /*
     * This function causes dependent instructions to be fetched
     * from the client's DAG starting from `from`.
     * */
    void do_runahead(CLIENT*, inst_ptr from);

    bool is_done(inst_ptr);

    /*
     * Returns true a correction is needed (teleportation failed).
     * Also, deletes the corresponding request.
     * */
    APPLY_MAGIC_STATE_RESULT apply_magic_state(inst_ptr, QUBIT* target);

    /*
     * Sets the `interrupted` flag of the corresponding request, which indicates
     * that this request is critical. If insufficient progress has been made in this
     * request, then the request is invalidated. 
     *
     * If the request is in the `request_queue_`, then it is always invalidated.
     *
     * Returns true on invalidation.
     * */
    bool interrupt_and_invalidate_if_necessary(inst_ptr);

    ssize_t lookahead_depth() const;
    double coverage() const;
    double timeliness() const;
private:
    /*
     * Retires the request, and if possible, places it into the `completion_buffer_`.
     * */
    void retire_request(request_type&);

    /*
     * Pins the given qubit to a request in `request_queue_`
     * */
    void allocate_free_qubit(QUBIT*);

    /*
     * Adds a request to the `request_queue_`.
     * */
    void enqueue_request(request_type&&);

    /*
     * This just calls `COMPUTE_SUBSYSTEM::current_cycle()`
     * */
    cycle_type current_cycle() const;

    void update_on_consumption(uint64_t uops, cycle_type rz_prep_time, cycle_type rz_idle_time);
};

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

} // namespace driver
} // namespace sim


#endif // SIM_DRIVER_RDR_h
